[package]
name = "mfem"
description = "A high-level Rust wrapper for MFEM"
readme = "README.md"
authors = ["Mate Kovacs <mkovaxx@gmail.com>"]
license = "MIT"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/mkovaxx/mfem-rs"

[dependencies]
cxx = "1.0.137"
autocxx = "0.28"
mfem-sys = { version = "0.2.0", path = "../mfem-sys" }
paste = "1.0"

[features]
bundled = ["mfem-sys/bundled"]
bundled-f32 = ["mfem-sys/bundled-f32"]

[dev-dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
